// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfYK34Wgjcsj3n6v-TAVat3tEnG2y_UvI',
    appId: '1:738625845314:web:8646e0f1974cb0252595db',
    messagingSenderId: '738625845314',
    projectId: 'testapp-ee39a',
    authDomain: 'testapp-ee39a.firebaseapp.com',
    databaseURL: 'https://testapp-ee39a-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-ee39a.appspot.com',
    measurementId: 'G-2WJ1VBPZL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwMcyzZYfZLOgT-MGjcS4nG3k8QaliKtU',
    appId: '1:738625845314:android:22835c1ce8d2cda92595db',
    messagingSenderId: '738625845314',
    projectId: 'testapp-ee39a',
    databaseURL: 'https://testapp-ee39a-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-ee39a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXYyW7XA2uuWSgSMlN6MZH4xwA_oeOu9Y',
    appId: '1:738625845314:ios:8c56792d905b406e2595db',
    messagingSenderId: '738625845314',
    projectId: 'testapp-ee39a',
    databaseURL: 'https://testapp-ee39a-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-ee39a.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXYyW7XA2uuWSgSMlN6MZH4xwA_oeOu9Y',
    appId: '1:738625845314:ios:74f4eeead4bf15292595db',
    messagingSenderId: '738625845314',
    projectId: 'testapp-ee39a',
    databaseURL: 'https://testapp-ee39a-default-rtdb.firebaseio.com',
    storageBucket: 'testapp-ee39a.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
